project_id: '815790'
api_token_env: 850bab94055b9eb7fed32b53436309ebbc1d0f4498880bfe90cf9779166b6d0c919ed04d708a1bc6
languages_mapping:
  en-US: en_US
  zh-CN: zh_CN
  ru-RU: ru_RU
  id-ID: id_ID
  en-IN: en_IN
base_url: 'https://api.crowdin.com'
files:
  - source: target/en_US.json
    translation: target/%two_letters_code%.json
    update_option: update_without_changes
