project_id: "815790"  # 必填：Crowdin 项目 ID（在项目设置中查看）
api_token_env: "850bab94055b9eb7fed32b53436309ebbc1d0f4498880bfe90cf9779166b6d0c919ed04d708a1bc6"     # 必填：API Token 的环境变量名（推荐通过环境变量传入 Token）
base_url: "https://api.crowdin.com"    # 默认API地址，一般无需修改

# 文件同步规则
files: 
  - source: "/origin/**/*.json"            # 源文件路径（支持 glob 模式）
    translation: "/%two_letters_code%/%original_file_name%"  # 翻译文件路径模板
    ignore: ["origin/ignore/**"]           # 可选：忽略的文件或目录
    update_option: "update_without_changes"  # 可选：文件更新策略
